sudo: required
language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - docker build -t $DOCKER_HUB_USER/follroad-external-event ./back-end/ExternalEventService

script:
  - docker run $DOCKER_HUB_USER/follroad-external-event npm test

after_success:
  - echo "$DOCKER_HUB_PSW" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  - docker push $DOCKER_HUB_USER/follroad-external-event

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
