sudo: required
services:
  - docker

after_success:
  - docker build - sanguo/follroad-externalEvent ./back-end/ExternalEventService
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push sanguo/follroad-externalEvent
