sudo: required
services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/follroad-external-event ./back-end/ExternalEventService

script:
  - docker run $DOCKER_USERNAME/follroad-external-event npm test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/follroad-external-event
