sudo: required
services:
  - docker

before_install:
  - docker build -t sanguo/follroad-external-event ./back-end/ExternalEventService

script:
  - docker run sanguo/follroad-external-event npm test

after_success:
  - docker build -t sanguo/follroad-external-event ./back-end/ExternalEventService
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sanguo/follroad-external-event
