version: "3"
services:
  event:
    build: ./back-end/EventService
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    links:
      - mariadb:database
    volumes:
      - ./back-end/EventService:/app
      - /app/node_modules
  message-queue:
    build: ./back-end/MessageQueueServiceProducer
    command: ["npm", "run", "dev"]
    ports:
      - "3001:3001"
    volumes:
      - ./back-end/MessageQueueServiceProducer:/app
      - /app/node_modules
  notification:
    build: ./back-end/NotificationService
    command: ["npm", "run", "dev"]
    ports:
      - "3002:3002"
    links:
      - mongodb
    volumes:
      - ./back-end/NotificationService:/app
      - /app/node_modules
  direction-record:
    build: ./back-end/DirectionRecordService
    command: ["npm", "run", "dev"]
    ports:
      - "3003:3003"
    links:
      - mongodb
    volumes:
      - ./back-end/DirectionRecordService:/app
      - /app/node_modules
  geometry:
    build: ./back-end/GeometryService
    command: ["npm", "run", "dev"]
    ports:
      - "3004:3004"
    volumes:
      - ./back-end/GeometryService:/app
      - /app/node_modules
  mariadb:
    image: mariadb
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: dev
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  # web:
  #   build: ./front-end
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./front-end:/app
  #     - /app/node_modules
volumes:
  mariadb:
  mongodb: