version: "3"
services:
  external-event-service:
    build: ./back-end/ExternalEventService
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    links:
      - external-event-db:database
    volumes:
      - ./back-end/ExternalEventService:/app
      - /app/node_modules
    environment:
      TZ: Asia/Bangkok
  external-event-db:
    image: mariadb
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - ./back-end/ExternalEventService/setup_database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: event
      TZ: Asia/Bangkok
