version: "3"
services:
  external-event:
    build: ./back-end/ExternalEventService
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    links:
      - mariadb:database
    volumes:
      - ./back-end/ExternalEventService:/app
      - /app/node_modules
    environment:
      TZ: Asia/Bangkok
  mariadb:
    image: mariadb
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./back-end/ExternalEventService/src/utils:/docker-entrypoint-initdb.d
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: dev
      TZ: Asia/Bangkok
  message-queue:
    build: ./back-end/MessageQueueServiceProducer
    command: ["npm", "run", "dev"]
    ports:
      - "3001:3001"
    volumes:
      - ./back-end/MessageQueueServiceProducer:/app
      - /app/node_modules
  notification:
    build: ./back-end/NotificationService
    command: ["npm", "run", "dev"]
    ports:
      - "3002:3002"
    links:
      - mongodb
    volumes:
      - ./back-end/NotificationService:/app
      - /app/node_modules
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  # test:
  #   build: ./back-end/Test
  #   command: ["npm", "run", "dev"]
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./back-end/Test:/app
  #     - /app/node_modules
  # web:
  #   build: ./front-end
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./front-end:/app
  #     - /app/node_modules
volumes:
  mongodb:
  mariadb:
