version: "3"
services:
  longdo-service:
    build: ./back-end/LongdoService
    ports:
      - "3000:3000"
    links:
      - longdo-db
  longdo-db:
    build: ./back-end/LongdoService/setup_database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
